#!/bin/sh
# Sets git token to a variable
GIT_TOKEN=$(git config --get-all remote.origin.url|sed -e 's/.*https:\/\/\(.*\)@.*/\1/')
# Removes git token
GIT_URL=$(git config --get-all remote.origin.url| sed -e "s/$GIT_TOKEN//")
# Opens URL
open -a "Google Chrome" "$GIT_URL"
